// virtualryan.client/src/app/resume-chat.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-resume-chat',
  templateUrl: './resume-chat.component.html',
  styleUrls: ['./resume-chat.component.css'],
  standalone: true, // Mark as standalone
  imports: [FormsModule] // Import FormsModule for ngModel
})
export class ResumeChatComponent {
  public chatQuestion: string = '';
  public chatResponse: string = '';
  public loading: boolean = false;

  constructor(private http: HttpClient) {}

  submitQuestion(): void {
    console.log('submitQuestion called with:', this.chatQuestion);
    if (!this.chatQuestion.trim()) {
      console.log('No question entered.');
      return;
    }
 
    this.loading = true;
    this.chatResponse = '';

    this.http.post(
      'Chat/AskQuestion',
      { question: this.chatQuestion },
      { responseType: 'text' }
    ).subscribe(
      (result) => {
        debugger;
        console.log('HTTP response received:', result);
        this.chatResponse = result;
        this.loading = false;
        console.log('chatResponse set to:', this.chatResponse);
      },
      (error) => {
        console.error('HTTP error:', error);
        this.chatResponse = 'Error getting response:' + error;
        this.loading = false;
      }
    );
  }
}

<h2>Resume Chat</h2>
<form (ngSubmit)="submitQuestion()" style="margin-bottom:2rem;">
  <textarea [(ngModel)]="chatQuestion" name="chatQuestion" rows="8" cols="80" placeholder="Ask a question about Ryan's resume..."></textarea>
  <br>
  <button type="submit" [disabled]="loading || !chatQuestion.trim()" class="logo">Submit</button>
</form>

@if (loading) {
<div><em>Loading response...</em></div>
}

@if (chatResponse && !loading) {
<div class="response">
  {{ chatResponse }}
</div>
}

// virtualryan.client/src/resume-chat.tsx
import { useState, useRef } from 'react';
import './resume-chat.css';

function ResumeChat() {
    const [chatQuestion, setChatQuestion] = useState<string>('');
    const [chatResponse, setChatResponse] = useState<string>('');
    const [loading, setLoading] = useState<boolean>(false);
    const formRef = useRef<HTMLFormElement>(null);

    const submitQuestion = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        console.log('submitQuestion called with:', chatQuestion);
        if (!chatQuestion.trim()) {
            console.log('No question entered.');
            return;
        }

        setLoading(true);
        setChatResponse('');

        try {
            const response = await fetch('/Chat/AskQuestion', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ question: chatQuestion }),
            });

            if (response.ok) {
                const result = await response.text();
                console.log('HTTP response received:', result);
                setChatResponse(result);
            } else {
                const errorText = await response.text();
                console.error('HTTP error:', errorText);
                setChatResponse('Error getting response: ' + errorText);
            }
        } catch (error) {
            console.error('Fetch error:', error);
            setChatResponse('Error getting response: ' + error);
        } finally {
            setLoading(false);
        }
    };

    // Listen for Enter (Return) key and submit if not Shift+Enter
    const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            if (formRef.current && chatQuestion.trim() && !loading) {
                formRef.current.requestSubmit();
            }
        }
    };

    return (
        <div>
            <h2>Resume Chat</h2>
            <form
                ref={formRef}
                onSubmit={submitQuestion}
                style={{ marginBottom: '2rem' }}
            >
                <textarea
                    id="chatQuestion"
                    value={chatQuestion}
                    onChange={(e) => setChatQuestion(e.target.value)}
                    onKeyDown={handleKeyDown}
                    name="chatQuestion"
                    rows={8}
                    cols={80}
                    placeholder="Ask a question about Ryan's resume..."
                />
                <br />
                <button type="submit" disabled={loading || !chatQuestion.trim()} className="logo">
                    Submit
                </button>
            </form>

            {loading && (
                <div className="loading-container">
                    <div className="spinner"></div>
                    <span>Loading response...</span>
                </div>
            )}

            {chatResponse && !loading && (
                <div className="response">
                    {chatResponse}
                </div>
            )}
        </div>
    );
}
export default ResumeChat;
